### ISSUE TITLE
Compatibilité SPIP V4

### ISSUE THREAD

**Issue by webetcaetera** [nhoizey/spip2markdown#1]
Modifier la la borne de compatibilité dans le paquet.xml vers V4 /  V6.0.0 Zippeur
+ 
mes_options.php Ajout de la constante 
`define('_DEV_VERSION_SPIP_COMPAT',"4.0.99"); `
+
 Config de zippeur 6.0.0 en utilisation de Zip et pas PclZip ni 7-zip

**Comment by nhoizey** [comment]
@webetcaetera merci ! 🙏

Du coup ça irait de changer juste en `compatibilite="[3.0.0;4.*]"` dans `paquet.xml` ?

```xml
<paquet
  prefix="spip2markdown"
  categorie="outil"
  version="0.2.9"
  etat="dev"
  logo="prive/themes/spip/images/spip2markdown-32.png"
  compatibilite="[3.0.0;4.*]">
  <nom>SPIP → Markdown</nom>
  <auteur lien="https://twitter.com/nhoizey">Nicolas Hoizey</auteur>
  <licence>MIT</licence>
  <necessite nom="saisies" compatibilite="[2.1.3;]" />
  <necessite nom="zippeur" compatibilite="[4.1.4;]" />
  <pipeline nom="affiche_gauche" action="affiche_gauche" inclure="spip2markdown_pipelines.php" />
</paquet>
```

Si je ne m'abuse, `<necessite nom="zippeur" compatibilite="[4.1.4;]" />` permet d'utiliser la v6.

Par contre, le `define('_DEV_VERSION_SPIP_COMPAT',"4.0.99");` reste-il utile s'il y a bien `compatibilite="[3.0.0;4.*]"` dans le plugin ?

**Comment by webetcaetera** [comment]
Oui, c'est ce que j'ai fait pour la compatibilité. (j'ai fait [4.0.0;4.*] au départ mais je viens de vérifier avec [3.0.0;4.*] ça roule. 
Pour zippeur ce n'était peut-être pas nécessaire de passer la compatibilité à 6.0 je viens de remplacer par [4.1.4;], rien n'a bougé.
Par contre pour il faut bien la constante sinon, l'install ne marche pas… Il doit falloir faire d'autres modifs dans le plugins pour qu'elle ne soit pas nécessaire, et c'est au dessus de mes compétences :-)

**Comment by webetcaetera** [comment]
Voilà ce que j'ai maintenant et tout fonctionne. 
```
<paquet
  prefix="spip2markdown"
  categorie="outil"
  version="0.2.9"
  etat="dev"
  logo="prive/themes/spip/images/spip2markdown-32.png"
  compatibilite="[3.0.0;4.*]">
  <nom>SPIP → Markdown</nom>
  <auteur lien="https://twitter.com/nhoizey">Nicolas Hoizey</auteur>
  <licence>MIT</licence>
  <necessite nom="saisies" compatibilite="[2.1.3;]" />
  <necessite nom="zippeur" compatibilite="[4.1.4;]" />
  <pipeline nom="affiche_gauche" action="affiche_gauche" inclure="spip2markdown_pipelines.php" />
</paquet>

```

**Comment by nhoizey** [comment]
C'est étrange, la doc dit que la constante n'est là que pour forcer la compatibilité avec un plugin dont la compatibilité n'est pas bonne : https://www.spip.net/fr_article6669.html

Donc avec la bonne valeur dans `compatibilite`, la constante ne devrait pas être nécessaire.

**Comment by nd-** [comment]
Tout à fait, mais le plugin Zippeur, lui, n'est pas indiqué compat 4.1 (uniquement 4.0 pour l'instant) : 
https://git.spip.net/spip-contrib-extensions/zippeur/src/branch/master/paquet.xml
C'est pour ça que la constante est utile dans ce cas.

Mais du coup, comme ton plugin nécessite Zippeur, si tu le passes compat 4.1 les gens qui voudraient l'installer vont se retrouver coincés s'ils n'utilisent pas la constante...

Mais bon, c'est peut être à la marge, et puis @webetcaetera si tu confirmes que Zippeur marche bien en 4.1 comme attendu, je peux le modifier en ce sens sur git.spip.net

**Comment by nhoizey** [comment]
@nd- ok, c'est plus clair, merci !

Si zippeur peut être indiqué compatible 4.1, ce sera bon, sinon j'ajouterai la mention de la constante dans mon readme.

**Comment by webetcaetera** [comment]
J'ai chargé le plugin Zippeur 6.0.0 et sans la constante ça ne fonctionnait pas. Je n'ai même pas essayé d'installer le 4.1. Mais je ne comprends peut-être pas votre question ?

**Comment by webetcaetera** [comment]
Oui, après relecture compris. Je ne savais plus de quelle version 4.1 vous parliez celle du plugin ou celle de spip !
Alors oui, le plugin 6.0 marche bien en 4.1 Spip. :)

**Comment by nd-** [comment]
Cool, merci @webetcaetera, je transmets à Maïeul, et s'il n'a pas le temps, je m'en occupe.
C'est aussi par ces retours là (tests validés par les utilisateurs) qu'on arrive à monter les versions de compat des plugins.

**Comment by maieul** [comment]
Merci pour les tests, j'ai releszé zipper v6.0.1 comme compatible SPIP 4.1

**Comment by nhoizey** [comment]
Super, merci pour votre aide ! 🙏
